apiVersion: v1
kind: Secret
data:
  # password Secret123
  KUSER_PWD: U2VjcmV0MTIz
metadata:
  name: kafkausers-secrets
type: Opaque
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: event-broker-dr
  name: kuser
  namespace: appdev-kafka
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          key: KUSER_PWD
          name: kafkausers-secrets
  authorization:
    type: simple
    acls:
    - host: '*'
      operation: All
      resource:
        name: '*'
        patternType: literal
        type: topic
      type: allow